import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { parse } from 'yaml';

const PAGE_EXT = /\.(md|mdx|mdoc)$/;
const ignored = (name) => name.startsWith('_') || name.startsWith('.');

function frontmatter(file) {
	const match = /^---\r?\n([\s\S]*?)\r?\n---/.exec(readFileSync(file, 'utf8'));
	if (!match) return {};
	try {
		return parse(match[1]) ?? {};
	} catch {
		return {};
	}
}

function containsPages(dir) {
	return readdirSync(dir, { withFileTypes: true }).some((e) =>
		ignored(e.name) ? false : e.isDirectory() ? containsPages(join(dir, e.name)) : PAGE_EXT.test(e.name),
	);
}

/** "02-getting-started" → "Getting started" */
export function humanize(name) {
	const clean = name.replace(/^\d+[-_. ]+/, '').replace(/[-_]+/g, ' ').trim();
	return clean.charAt(0).toUpperCase() + clean.slice(1);
}

const byNumericPrefixThenName = (a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' });

/**
 * Default sidebar: pages at the root of docs/ (sorted by `sidebar.order`, then by name),
 * followed by one autogenerated group per subdirectory. Directories without pages (images…) are skipped.
 */
export function autoSidebar(docsDir) {
	if (!existsSync(docsDir)) return [];
	const entries = readdirSync(docsDir, { withFileTypes: true }).filter((e) => !ignored(e.name));

	const pages = entries
		.filter((e) => e.isFile() && PAGE_EXT.test(e.name))
		.map((e) => {
			const fm = frontmatter(join(docsDir, e.name));
			const slug = e.name.replace(PAGE_EXT, '').toLowerCase();
			return { slug, order: fm.sidebar?.order ?? (slug === 'index' ? -Infinity : Infinity), hidden: fm.sidebar?.hidden === true };
		})
		.filter((p) => !p.hidden)
		.sort((a, b) => a.order - b.order || byNumericPrefixThenName(a.slug, b.slug))
		.map(({ slug }) => slug);

	const groups = entries
		.filter((e) => e.isDirectory() && containsPages(join(docsDir, e.name)))
		.map((e) => e.name)
		.sort(byNumericPrefixThenName)
		.map((dir) => ({ label: humanize(dir), items: [{ autogenerate: { directory: dir } }] }));

	return [...pages, ...groups];
}

/**
 * Translate the docs.yml sidebar into Starlight syntax. docs.yml accepts the short form
 * `{ label, autogenerate }`, which Starlight (≥ 0.39) expresses as `{ label, items: [{ autogenerate }] }`.
 */
export function toStarlightSidebar(items) {
	return items.map((item) => {
		if (typeof item !== 'object') return item;
		if ('autogenerate' in item && 'label' in item) {
			const { autogenerate, ...group } = item;
			return { ...group, items: [{ autogenerate }] };
		}
		if ('items' in item) return { ...item, items: toStarlightSidebar(item.items) };
		return item;
	});
}

/** Signature of the top-level tree: when it changes, the sidebar must be regenerated. */
export function topLevelSignature(docsDir) {
	if (!existsSync(docsDir)) return '';
	return readdirSync(docsDir)
		.filter((n) => !ignored(n))
		.map((n) => {
			const p = join(docsDir, n);
			const st = statSync(p);
			return st.isDirectory() ? `${n}/${containsPages(p)}` : PAGE_EXT.test(n) ? `${n}:${st.mtimeMs}` : '';
		})
		.join('|');
}
